# -*- mode: ruby -*-
# vi: set ft=ruby :
#
# This Vagrantfile is not intended to be used during project evaluation,
# but rather as a reference for the configuration of the VM used for
# development and testing.

GUEST_NAME = "bookworm"
GUEST_IP = "192.168.56.110"

Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.vm.provider "libvirt" do |libvirt|
    libvirt.cpus = 2
    libvirt.memory = 2048
    libvirt.default_prefix = ""
    libvirt.driver = "kvm"
  end

  config.vm.define GUEST_NAME do |guest|
    guest.vm.hostname = GUEST_NAME
    guest.vm.network "private_network", ip: GUEST_IP
    guest.vm.provision "shell", path: "bootstrap.sh"
  end
end
